name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm i -f && npm install --save @revopush/react-native-code-push

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    timeout-minutes: 120
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node modules
        run: npm i -f && npm install --save @revopush/react-native-code-push

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Android Release (Debug Signed)
        working-directory: android
        run: ./gradlew assembleRelease --no-daemon

      - name: Upload Android APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk # Built APK file
          expire_in: 1 week  # APK expires after 1 week


  ios-build:
    name: iOS Build
    runs-on: macos-latest
    timeout-minutes: 120
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node modules
        run: npm i -f && npm install --save @revopush/react-native-code-push

      - name: Install Pods
        working-directory: ios
        run: pod install

      - name: Build iOS (Debug Simulator)
        working-directory: ios
        run: |
          xcodebuild -workspace CodePush.xcworkspace \
            -scheme CodePush \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            clean build CODE_SIGNING_ALLOWED=NO
